version: '3.8'

services:
  postgres-iamco:
    image: postgres:15
    container_name: iamco_db
    environment:
      POSTGRES_DB: iamco_db
      POSTGRES_USER: iamco
      POSTGRES_PASSWORD: iamcopass
    ports:
      - "5432:5432"
    volumes:
      - iamco_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iamco_network

volumes:
  iamco_data:


networks:
  iamco_network:
